version: 2
jobs:
  install-job:
    docker:
      - image: circleci/node:10.14
    working_directory: ~/react-robust-ui
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/react-robust-ui
          paths:
            - node_modules/*

  test-job:
    docker:
      - image: circleci/node:10.14

    working_directory: ~/react-robust-ui

    steps:
      - checkout
      - attach_workspace:
          at: ~/react-robust-ui
      - run: yarn test

  lint-job:
    docker:
      - image: circleci/node:10.14

    working_directory: ~/react-robust-ui

    steps:
      - checkout
      - attach_workspace:
          at: ~/react-robust-ui
      - run: yarn lint

  build-job:
    docker:
      - image: circleci/node:10.14

    working_directory: ~/react-robust-ui

    steps:
      - checkout
      - attach_workspace:
          at: ~/react-robust-ui
      - run: yarn build
      - persist_to_workspace:
          root: ~/react-robust-ui
          paths:
            - lib/*

  size-job:
    docker:
      - image: circleci/node:10.14

    working_directory: ~/react-robust-ui

    steps:
      - checkout
      - attach_workspace:
          at: ~/react-robust-ui
      - run: yarn size

workflows:
  version: 2
  build-deploy:
    jobs:
      - install-job
      - build-job:
          requires:
            - install-job
      - test-job:
          requires:
            - install-job
      - lint-job:
          requires:
            - install-job
      - size-job:
          requires:
            - build-job
